name: Gradle Build

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  pack:
    strategy:
      matrix:
        os: [ windows-latest, macOS-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'
          distribution: 'zulu'
          java-package: 'jdk'

      - name: Init gradle
        uses: gradle/gradle-build-action@v2.8.0
        with:
          gradle-version: 8.2.1

      - run:
          gradle build

      - run:
          gradle pack

      - name: Upload
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Package
          path: build/packages

  release:
    needs: [ pack ]
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Download
        uses: actions/download-artifact@v2.1.1
        with:
          name: Package
          path: out

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files:
            ./**/**.jar
