name: Gradle Build

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  pack:
    strategy:
      matrix:
        os: [ windows-latest, macOS-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Init gradle
        uses: gradle/gradle-build-action@v2.11.1
        with:
          gradle-version: 8.5

      - name: Gradle Build
        run: gradle build

      - name: Upload
        uses: actions/upload-artifact@v4.1.0
        with:
          name: Package
          path: packages

  release:
    needs: [ pack ]
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Download
        uses: actions/download-artifact@v4.1.1
        with:
          name: Package
          path: out

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./**/**.dmg
            ./**/**.msi
            ./**/**.jar
